### ISSUE TITLE
'csharp' name missing for aliases

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/ColorCode-Universal#1]
I think GitHub uses `csharp` as an identifier:

```csharp
public class Test {
...
}
```

But it's not looked for here: https://github.com/WilliamABradley/ColorCode-Universal/blob/master/ColorCode.Core/Compilation/Languages/CSharp.cs#L117 (which I think is what's used for the matching?)

**Comment by WilliamABradley** [comment]
Those just contain the Alternate Aliases, the Language ID is `csharp`, which is checked against first.

If you look at the Xml Language, it checks xml first, and I added XAML and AXML to the list. Some languages have no Aliases, like I believe Fortran.

**Comment by michael-hawker** [comment]
Is that the [LanguageId](https://github.com/WilliamABradley/ColorCode-Universal/blob/master/ColorCode.Core/Common/LanguageId.cs#L12)?  As they have `c#` instead of `csharp` so we'd need the other as the alias still, eh?

**Comment by WilliamABradley** [comment]
Thats true, I'll fix that.
