### ISSUE TITLE
Add support for Python, MATLAB, Julia and other scientific / mathematical languages

### ISSUE THREAD

**Issue by Calman102** [CommunityToolkit/ColorCode-Universal#14]
Python in particular. It's the most popularly used language according to PYPL.

**Comment by michael-hawker** [comment]
Thanks for the issue @Calman102! I'm surprised too, I didn't realize Python was missing.

The Languages are controlled by files here: https://github.com/windows-toolkit/ColorCode-Universal/tree/master/ColorCode.Core/Compilation/Languages

Please feel free to submit a PR to include them if you're up for it. If not we can add the `Help Wanted` tag to get some assistance from our community.

**Comment by Calman102** [comment]
After much effort learning how to use regular expressions, I did the syntax highlighting for Python and MATLAB. PR here: #15 

I'm not familiar enough with Julia yet to do that myself, and I would also like to see R support at some stage.
