### ISSUE TITLE
Relicense Project to MIT

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/ColorCode-Universal#20]
The ColorCode maintainers are considering changing the licensing on the project. Currently, the project is MS-PL, but in order to spur wider adoption and possibly a greater contributor base, we'd like to change the license to MIT, a highly-popular OSI-approved license. This license change will also align with the rest of the .NET Foundation work we do within the Toolkit organization. This contemplated license change is in part why we haven't merged any pending PRs within the project since we took ownership of the project.

We are checking with all past contributors to get an acknowledgement that they agree to this license change. Can you please respond to this issue with your agreement (or indicating you do not agree that your contributions may be licensed under MIT)?

---

FYI @arthurrump @csainty 

@lukehoban according to your GitHub you used to work at Microsoft, so I believe you're the same Luke Hoban who made contributions previously when the project was on GitHub as part of your work at the company?

@WilliamABradley @daanx @bashirsouid-ms @csano @half-ogre (also attributed as AnglicanGeek/Drew Miller from CodePlex times) - I know I've spoken with you offline about this, but having a formal response here from you too would help for completeness and history.

Thanks!

**Comment by WilliamABradley** [comment]
👍

**Comment by half-ogre** [comment]
>  but having a formal response here from you too would help for completeness and history.

Sounds good. Thanks for reaching out!

**Comment by csainty** [comment]
Do it!

**Comment by arthurrump** [comment]
I agree 👍

**Comment by capjan** [comment]
Now, it's one year later!
What about the progress to relicense this project as MIT?

**Comment by michael-hawker** [comment]
Thanks for the poke @capjan. Things got slowed down by us shifting focus to support the release of the Windows App SDK last year, changes in the .NET Foundation, and work we've been doing for understanding how to maintain the toolkit in the future.

However, in more positive news, we may have cleared our last blocker in this space to move forward with the license change finally. 🎉 I'll be opening up a PR soon with the changes to move forward on this later next week or early in August, so we can close this out once and for all!

**Comment by michael-hawker** [comment]
Hey everyone, I should be opening a PR shortly to switch over the license, all the known blockers have been resolved! 🎉

**Comment by michael-hawker** [comment]
Hey everyone, thanks for your assistance and cooperation with this! It's finally done! 🎉🎉🎉
